import test from "node:test";
import assert from "node:assert/strict";
import {
  assertCanonicalMediaInput, preflightReferenceAsset, mediaConfigurationFingerprint,
  evaluateMediaConfigurationAuthorization, evaluateCaptionVerification,
  evaluateVisualContinuity, InMemoryVideoSubmissionLedger, assertCanonicalFinalMedia,
  assertCanonicalAnalyticsJoin, assertLearningEvidenceBinding,
  assertCanonicalNewProductionArtifact, assertMediaAccountingIdentity,
} from "../dist/index.js";

const sha = "a".repeat(64);
const mediaInput = { projectId: "p", contentId: "c", workflowId: "w", writerArtifactId: "writer", scenePlanArtifactId: "scenes", visualDirectionArtifactId: "visual", scriptIdentity: "script", narrationText: "text", voiceId: "voice", aspectRatio: "9:16", sceneIds: ["s1", "s2"], ownerApprovalId: "approval" };
const ref = { referenceAssetId: "ref", projectId: "p", contentId: "c", subjectId: "subject", mimeType: "image/png", sha256: sha, suitability: "APPROVED", bytes: 100, width: 512, height: 512, transport: { kind: "HTTPS_URL", url: "https://assets.example/ref.png", expiresAt: "2027-01-01T00:00:00.000Z" } };
const refContext = { projectId: "p", contentId: "c", subjectId: "subject", now: "2026-09-28T00:00:00.000Z", providerAcceptsDataUrl: false, maxBytes: 1000, minWidth: 256, minHeight: 256 };
const config = { voiceId: "v1", ttsProvider: "tts", ttsModel: "m1", imageProvider: "img", imageModel: "i1", videoProvider: "vid", videoModel: "v1" };
const intent = { logicalExecutionId: "exec", sourceVisualArtifactId: "visual", sourceVisualSha256: sha, promptFingerprint: "prompt", provider: "wan", model: "wan-1", expectedDurationMs: 5000, aspectRatio: "9:16" };

test("A: canonical media input validates and rejects loose identities", () => { assert.doesNotThrow(() => assertCanonicalMediaInput(mediaInput)); assert.throws(() => assertCanonicalMediaInput({ ...mediaInput, visualDirectionArtifactId: "" }), /MEDIA_INPUT_REQUIRED/); });
test("B/C: reference transport accepts provider-safe HTTPS and rejects local paths before transport", () => { assert.equal(preflightReferenceAsset(ref, refContext).ok, true); assert.deepEqual(preflightReferenceAsset({ ...ref, transport: { kind: "LOCAL_PATH", path: "C:\\x.png" } }, refContext), { ok: false, failure: "REFERENCE_UNAVAILABLE", reason: "REMOTE_PROVIDER_CANNOT_FETCH_LOCAL_PATH" }); });
test("D/E: media configuration identity is deterministic and changed voice requires Owner reauthorization", () => { const frozen = { ...config, fingerprint: mediaConfigurationFingerprint(config), authorizedBy: "owner", authorizationId: "auth" }; assert.equal(evaluateMediaConfigurationAuthorization(frozen, config), "AUTHORIZED"); assert.equal(evaluateMediaConfigurationAuthorization(frozen, { ...config, voiceId: "v2" }), "OWNER_REAUTH_REQUIRED"); });
test("H: caption sidecar is not burned-in proof", () => { assert.equal(evaluateCaptionVerification({ required: true, sidecarPresent: true }), "SIDECAR_ONLY"); assert.equal(evaluateCaptionVerification({ required: true, sidecarPresent: true, rendererBurnInReceipt: { outputSha256: sha, captionTrackSha256: "b".repeat(64) }, pixelSemanticReview: "UNAVAILABLE" }), "HUMAN_REVIEW_REQUIRED"); });
test("K/Q: metadata continuity and semantic QA fail honestly to human review", () => { assert.equal(evaluateVisualContinuity({ requiredSubjectIds: ["a"], boundReferenceSubjectIds: ["a"], visualMode: "photo", expectedVisualMode: "photo", semanticInspection: "UNAVAILABLE" }), "HUMAN_REVIEW_REQUIRED"); });
test("L/M/N: video intent precedes submit and ambiguous outcome blocks blind retry until reconciliation", () => { const ledger = new InMemoryVideoSubmissionLedger(); assert.equal(ledger.persistIntent(intent).state, "INTENT_PERSISTED"); assert.equal(ledger.maySubmit("exec"), true); assert.equal(ledger.markTransportStarted("exec").state, "SUBMITTING"); ledger.markAmbiguous("exec"); assert.equal(ledger.maySubmit("exec"), false); assert.equal(ledger.reconcile("exec").state, "RECONCILIATION_REQUIRED"); assert.equal(ledger.reconcile("exec", "provider-job").state, "ACKNOWLEDGED"); assert.equal(ledger.get("exec").providerJobId, "provider-job"); assert.equal(ledger.maySubmit("exec"), false); });
test("O/P: canonical final media requires integrity, lineage, narration fit and honest caption state", () => { const final = { artifactId: "fm", projectId: "p", contentId: "c", workflowId: "w", storageReference: "object://fm", bytes: 1000, sha256: sha, durationMs: 5000, width: 1080, height: 1920, videoCodec: "h264", audioCodec: "aac", compositionStrategy: "timeline-v1", sourceArtifactIds: ["n", "t", "v"], captionMode: "HUMAN_REVIEW_REQUIRED", narrationFit: "PASS" }; assert.doesNotThrow(() => assertCanonicalFinalMedia(final)); assert.throws(() => assertCanonicalFinalMedia({ ...final, bytes: 0 }), /FINAL_MEDIA_TECHNICAL_INVALID/); });
test("R: legacy thumbnail/video kinds are read-only for new production", () => { assert.throws(() => assertCanonicalNewProductionArtifact("thumbnail_report"), /LEGACY_MEDIA_NEW_WRITE_FORBIDDEN/); assert.throws(() => assertCanonicalNewProductionArtifact("video_report"), /LEGACY_MEDIA_NEW_WRITE_FORBIDDEN/); assert.doesNotThrow(() => assertCanonicalNewProductionArtifact("final_media_artifact")); });
test("Z: canonical analytics join requires every new-production identity", () => { const join = { projectId: "p", contentId: "c", workflowId: "w", finalMediaArtifactId: "fm", finalMediaSha256: sha, publishedReportId: "pub-report", providerPublicationId: "video", channelId: "channel" }; assert.doesNotThrow(() => assertCanonicalAnalyticsJoin(join)); assert.throws(() => assertCanonicalAnalyticsJoin({ ...join, publishedReportId: "" }), /ANALYTICS_JOIN_REQUIRED/); });
test("AB/AD/AE: learning may cite only observed metrics", () => { assert.doesNotThrow(() => assertLearningEvidenceBinding({ views: 10, likes: 2 }, ["views"])); assert.throws(() => assertLearningEvidenceBinding({ views: 10 }, ["revenue"]), /LEARNING_METRIC_NOT_OBSERVED/); });
test("cost provenance preserves unknown and marks stubs not billable", () => { assert.doesNotThrow(() => assertMediaAccountingIdentity({ callKind: "VIDEO", reservationId: "r", logicalExecutionId: "e", costUsd: null, costProvenance: "UNKNOWN" })); assert.doesNotThrow(() => assertMediaAccountingIdentity({ callKind: "IMAGE", reservationId: "r", logicalExecutionId: "e", costUsd: 0, costProvenance: "STUBBED_NOT_BILLABLE" })); assert.throws(() => assertMediaAccountingIdentity({ callKind: "TTS", reservationId: "r", logicalExecutionId: "e", costUsd: 0, costProvenance: "UNKNOWN" }), /UNKNOWN_COST_MUST_REMAIN_NULL/); });
