import { deepStrictEqual, equal, match, ok, rejects, throws } from "node:assert";
import { readFile } from "node:fs/promises";
import { test } from "node:test";
import { BoundedStructuralValidationError } from "@ai-media-factory/runtime";
import { createStrategyCouncilV2SpecialistAgent, strategyCouncilV2OutputInstructions, strategyCouncilV2Schema, STRATEGY_COUNCIL_V2_EXAMPLES, STRATEGY_COUNCIL_V2_SYSTEM_PROMPTS, validateStrategyCouncilSpecialistV2 } from "../dist/strategy-council-v2-specialists.js";

const refs=[{artifactId:"canonical-upstream",kind:"research_report"}];
const base=(specialist,contract)=>({contract,specialist,status:"COMPLETED",objective:"Decision-ready Strategy Council analysis",recommendations:["Proceed with a bounded evidence-led test"],risks:["Evidence remains limited"],tradeoffs:["Breadth versus production repeatability"],assumptionsAndUnknowns:[{statement:"Retention is not observed",classification:"UNKNOWN"}],sourceArtifactReferences:refs});
const fixtures={
 writer:{...base("writer","STRATEGY_COUNCIL_WRITER_V2"),storytellingArchitecture:"A repeatable narrative system",hookMechanics:["Immediate unresolved tension"],repeatableSeries:["Evidence-led historical moments"],shortFormSuitability:"One idea per episode",emotionalDepth:"Human stakes support attention",educationalDepth:"Verified context supports value",globalComprehension:"Visual clarity minimizes language dependence",languageStrategy:"Test accessible narration and captions",productionRepeatability:"Use reusable editorial stages",contentFatigueRisk:"Rotate stakes and narrative forms",representativeDirections:["Character-led history"]},
 seo:{...base("seo","STRATEGY_COUNCIL_SEO_V2"),discoverabilityArchitecture:"Topic-led discovery without unsupported volumes",topicFamilies:["Historical turning points"],topicFraming:["Questions and consequences"],discoveryIntent:"Curiosity and learning",platformImplications:["Instagram Reels","YouTube Shorts","TikTok"].map(platform=>({platform,implication:"Adapt metadata and opening framing natively"})),evergreenTrendBalance:"Evergreen core with selective trends",titleCaptionPrinciples:["Lead with a clear topic promise"],saturationRisks:["Generic history framing"]},
 brand:{...base("brand","STRATEGY_COUNCIL_BRAND_V2"),positioning:"Evidence-led cinematic knowledge",audiencePromise:"Clear memorable stories",differentiation:"Transparent evidence and emotional clarity",identityDirection:"HYBRID",identityRationale:"Human editorial trust without mandatory on-camera delivery",trustStrategy:"Show evidence classifications",memorabilityStrategy:"Consistent narrative grammar",extensibility:"Supports adjacent knowledge territories",visualDirection:"Recognizable restrained cinematic system",channelArchitectureRelationship:"One launch identity before portfolio expansion"},
 growth:{...base("growth","STRATEGY_COUNCIL_GROWTH_V2"),platformPriority:["Instagram Reels","YouTube Shorts","TikTok"].map((platform,i)=>({platform,priority:i+1,rationale:"Native learning priority"})),launchSequence:["Launch one focused channel"],cadenceDirection:"Sustainable evidence-led cadence",experimentationFramework:["Test one variable at a time"],crossPlatformReuse:"Reuse the core while adapting packaging",acquisitionMechanics:["Topic entry points"],retentionMechanics:["Open loops with factual payoff"],tractionSignals:["Completion and repeat viewing when available"],scalingGates:["Stable quality and repeatable production"],channelArchitectureImplications:"Phase expansion after evidence",expansionTriggers:["Repeatable positive signals"],deferredActions:["Additional channels"]},
 finance:{...base("finance","STRATEGY_COUNCIL_FINANCE_V2"),lowestPracticalLaunchBudget:"Use owned tools first; actual provider costs UNKNOWN",fixedCostCategories:["Existing software subscriptions if any"],variableCostCategories:["Generation usage at UNKNOWN actual cost"],toolProductionCostExposure:["Provider pricing remains UNKNOWN"],lowCostStartingOptions:["Manual editorial review"],laterPaidUpgrades:["Automation after demonstrated demand"],monetizationRoutes:["Affiliate and digital products as scenarios"],monetizationDependencies:["Audience trust and conversion evidence"],reinvestmentStrategy:"Reinvest after realized revenue",breakEvenConsiderations:"Track attributable cash costs",financialScalingGates:["Positive contribution evidence"],milestones:[100,1000,10000].map(monthlyUsd=>({monthlyUsd,economics:"Scenario, not guarantee",requirements:"Evidence-led operating capacity",risks:"Conversion remains unknown"}))},
};
fixtures.writer.repeatableSeries = [{series:"Evidence-led moments",format:"Short-form narrative series",strategicPurpose:"Repeatable learning"}];
for (const milestone of fixtures.finance.milestones) milestone.economics = "Scenario with uncertain outcome";
const context={workflowId:"wf",correlationId:"corr",executionId:"exec",agentId:"writer",stageId:"stage",attempt:1,metadata:{}};
const signal={aborted:false,throwIfCancelled(){},onCancelled(){return()=>{};}};

for(const id of Object.keys(fixtures)){
 test(`${id} V2 contract, prompt, structural and semantic validation`,()=>{ok(STRATEGY_COUNCIL_V2_SYSTEM_PROMPTS[id].length>100);const schema=strategyCouncilV2Schema(id),instructions=strategyCouncilV2OutputInstructions(id);for(const key of schema.required)ok(instructions.includes(key));deepStrictEqual(validateStrategyCouncilSpecialistV2(id,STRATEGY_COUNCIL_V2_EXAMPLES[id]),STRATEGY_COUNCIL_V2_EXAMPLES[id]);deepStrictEqual(validateStrategyCouncilSpecialistV2(id,fixtures[id]),fixtures[id]);const invalid={...fixtures[id]};delete invalid.objective;throws(()=>validateStrategyCouncilSpecialistV2(id,invalid),BoundedStructuralValidationError);});
 test(`${id} governed adapter selects gpt-5.6-sol and one nonempty system prompt`,async()=>{let calls=0,captured;const agent=createStrategyCouncilV2SpecialistAgent(id,async(_ctx,request)=>{calls++;captured=request;return {output:fixtures[id],raw:JSON.stringify(fixtures[id]),usage:{inputTokens:1,outputTokens:1,costUsd:0},model:"gpt-5.6-sol",provider:"agentrouter-openai",latencyMs:1};});const out=await agent.executeAgent({context,input:{strategyMode:"PRE_PUBLICATION_STRATEGY",agentRouterModelOverride:"gpt-5.6-sol",validatedArtifacts:[{artifactId:"canonical-upstream",kind:"research_report",producerAgent:"research",payload:{bounded:true}}]}},signal);equal(calls,1);equal(captured.model,"gpt-5.6-sol");equal(captured.system,STRATEGY_COUNCIL_V2_SYSTEM_PROMPTS[id]);deepStrictEqual(out.output,fixtures[id]);});
}

test("semantic boundaries reject naming, fabricated SEO volume, guarantees, and invalid finance milestones",()=>{throws(()=>validateStrategyCouncilSpecialistV2("brand",{...fixtures.brand,positioning:"Final name: Viral Forge"}),/naming/);throws(()=>validateStrategyCouncilSpecialistV2("seo",{...fixtures.seo,discoverabilityArchitecture:"search volume: 50000"}),/metric/);throws(()=>validateStrategyCouncilSpecialistV2("growth",{...fixtures.growth,recommendations:["Guaranteed virality"]}),/guarantee/);throws(()=>validateStrategyCouncilSpecialistV2("finance",{...fixtures.finance,milestones:fixtures.finance.milestones.slice(0,2)}),/finance/);});

test("mock pipeline fails closed and never invokes downstream after a validation failure",async()=>{const order=[];for(const id of ["writer","seo","brand","growth","finance"]){if(id==="brand")break;order.push(id);if(id==="seo"){const bad={...fixtures.seo,recommendations:["Guaranteed discovery"]};throws(()=>validateStrategyCouncilSpecialistV2(id,bad),/guarantee/);break;}}deepStrictEqual(order,["writer","seo"]);ok(!order.includes("brand")&&!order.includes("finance"));});

test("continuation starts at fresh-5 Writer, scopes Claude to Writer, and never schedules Research or Planner",async()=>{const source=await readFile(new URL("../../../work/run-v2-council-continuation-gpt56sol.mjs",import.meta.url),"utf8");const stageBlock=source.slice(source.indexOf("const stages"),source.indexOf("const now"));match(stageBlock,/writer-strategy-v2-owner-authorized-fresh-5-claude-opus-4-8/);match(stageBlock,/writerModel/);match(stageBlock,/seo-strategy-v2-owner-authorized-gpt56sol/);match(stageBlock,/downstreamModel/);ok(!stageBlock.includes('"research"'));ok(!stageBlock.includes('"planner"'));match(source,/required\.planner/);match(source,/DOWNSTREAM_EXECUTION_RECONCILIATION_REQUIRED/);});
