import type { CancellationToken, ExecutionContext, ExecutionRequest, ExecutionResponse, Json, JsonSchema } from "@ai-media-factory/runtime";
import { BoundedStructuralValidationError, boundedStructuralDiagnostics } from "@ai-media-factory/runtime";

export type StrategyCouncilV2Specialist = "writer" | "seo" | "brand" | "growth" | "finance";
type EvidenceClass = "KNOWN" | "OBSERVED" | "INFERRED" | "ASSUMED" | "UNKNOWN";
interface Envelope { contract:string; specialist:StrategyCouncilV2Specialist; status:"COMPLETED"; objective:string; recommendations:readonly string[]; risks:readonly string[]; tradeoffs:readonly string[]; assumptionsAndUnknowns:readonly {statement:string;classification:EvidenceClass}[]; sourceArtifactReferences:readonly {artifactId:string;kind:string}[] }
export interface StrategyCouncilWriterV2 extends Envelope { contract:"STRATEGY_COUNCIL_WRITER_V2"; specialist:"writer"; storytellingArchitecture:string; hookMechanics:readonly string[]; repeatableSeries:readonly {series:string;format:string;strategicPurpose:string}[]; shortFormSuitability:string; emotionalDepth:string; educationalDepth:string; globalComprehension:string; languageStrategy:string; productionRepeatability:string; contentFatigueRisk:string; representativeDirections:readonly string[] }
export interface StrategyCouncilSEOV2 extends Envelope { contract:"STRATEGY_COUNCIL_SEO_V2"; specialist:"seo"; discoverabilityArchitecture:string; topicFamilies:readonly string[]; topicFraming:readonly string[]; discoveryIntent:string; platformImplications:readonly {platform:"Instagram Reels"|"YouTube Shorts"|"TikTok";implication:string}[]; evergreenTrendBalance:string; titleCaptionPrinciples:readonly string[]; saturationRisks:readonly string[] }
export interface StrategyCouncilBrandV2 extends Envelope { contract:"STRATEGY_COUNCIL_BRAND_V2"; specialist:"brand"; positioning:string; audiencePromise:string; differentiation:string; identityDirection:"FACELESS"|"PERSONAL_BRAND"|"HYBRID"; identityRationale:string; trustStrategy:string; memorabilityStrategy:string; extensibility:string; visualDirection:string; channelArchitectureRelationship:string }
export interface StrategyCouncilGrowthV2 extends Envelope { contract:"STRATEGY_COUNCIL_GROWTH_V2"; specialist:"growth"; platformPriority:readonly {platform:"Instagram Reels"|"YouTube Shorts"|"TikTok";priority:number;rationale:string}[]; launchSequence:readonly string[]; cadenceDirection:string; experimentationFramework:readonly string[]; crossPlatformReuse:string; acquisitionMechanics:readonly string[]; retentionMechanics:readonly string[]; tractionSignals:readonly string[]; scalingGates:readonly string[]; channelArchitectureImplications:string; expansionTriggers:readonly string[]; deferredActions:readonly string[] }
export interface StrategyCouncilFinanceV2 extends Envelope { contract:"STRATEGY_COUNCIL_FINANCE_V2"; specialist:"finance"; lowestPracticalLaunchBudget:string; fixedCostCategories:readonly string[]; variableCostCategories:readonly string[]; toolProductionCostExposure:readonly string[]; lowCostStartingOptions:readonly string[]; laterPaidUpgrades:readonly string[]; monetizationRoutes:readonly string[]; monetizationDependencies:readonly string[]; reinvestmentStrategy:string; breakEvenConsiderations:string; financialScalingGates:readonly string[]; milestones:readonly {monthlyUsd:100|1000|10000;economics:string;requirements:string;risks:string}[] }
export type StrategyCouncilSpecialistV2Output = StrategyCouncilWriterV2 | StrategyCouncilSEOV2 | StrategyCouncilBrandV2 | StrategyCouncilGrowthV2 | StrategyCouncilFinanceV2;

const stringSchema:JsonSchema = { type:"string" };
const stringArray:JsonSchema = { type:"array", minItems:1, maxItems:12, items:stringSchema };
const assumptions:JsonSchema = { type:"array", minItems:1, maxItems:12, items:{ type:"object", additionalProperties:false, properties:{ statement:stringSchema, classification:{type:"string",enum:["KNOWN","OBSERVED","INFERRED","ASSUMED","UNKNOWN"]} }, required:["statement","classification"] } };
const references:JsonSchema = { type:"array", minItems:1, maxItems:7, items:{ type:"object", additionalProperties:false, properties:{artifactId:stringSchema,kind:stringSchema},required:["artifactId","kind"] } };
const commonProperties:Record<string,Json> = { specialist:stringSchema, status:{type:"string",enum:["COMPLETED"]}, objective:stringSchema, recommendations:stringArray, risks:stringArray, tradeoffs:stringArray, assumptionsAndUnknowns:assumptions, sourceArtifactReferences:references };
const commonRequired = ["contract","specialist","status","objective","recommendations","risks","tradeoffs","assumptionsAndUnknowns","sourceArtifactReferences"];
const objectSchema = (properties:Record<string,Json>, required:string[], extra:Record<string,Json>={}) => ({type:"object",additionalProperties:false,properties,required,...extra}) as JsonSchema;

const schemas:Record<StrategyCouncilV2Specialist,JsonSchema> = {
  writer: objectSchema({ contract:{type:"string",enum:["STRATEGY_COUNCIL_WRITER_V2"]}, ...commonProperties,
    specialist:{type:"string",enum:["writer"]}, storytellingArchitecture:stringSchema, hookMechanics:stringArray,
    repeatableSeries:{type:"array",minItems:1,maxItems:10,items:{type:"object",additionalProperties:false,properties:{series:stringSchema,format:stringSchema,strategicPurpose:stringSchema},required:["series","format","strategicPurpose"]}},
    shortFormSuitability:stringSchema, emotionalDepth:stringSchema, educationalDepth:stringSchema, globalComprehension:stringSchema, languageStrategy:stringSchema, productionRepeatability:stringSchema, contentFatigueRisk:stringSchema, representativeDirections:stringArray,
  }, [...commonRequired,"storytellingArchitecture","hookMechanics","repeatableSeries","shortFormSuitability","emotionalDepth","educationalDepth","globalComprehension","languageStrategy","productionRepeatability","contentFatigueRisk","representativeDirections"]),
  seo: objectSchema({ contract:{type:"string",enum:["STRATEGY_COUNCIL_SEO_V2"]}, ...commonProperties,
    specialist:{type:"string",enum:["seo"]}, discoverabilityArchitecture:stringSchema, topicFamilies:stringArray, topicFraming:stringArray, discoveryIntent:stringSchema,
    platformImplications:{type:"array",minItems:3,maxItems:3,items:{type:"object",additionalProperties:false,properties:{platform:{type:"string",enum:["Instagram Reels","YouTube Shorts","TikTok"]},implication:stringSchema},required:["platform","implication"]}},
    evergreenTrendBalance:stringSchema,titleCaptionPrinciples:stringArray,saturationRisks:stringArray,
  }, [...commonRequired,"discoverabilityArchitecture","topicFamilies","topicFraming","discoveryIntent","platformImplications","evergreenTrendBalance","titleCaptionPrinciples","saturationRisks"]),
  brand: objectSchema({ contract:{type:"string",enum:["STRATEGY_COUNCIL_BRAND_V2"]}, ...commonProperties,
    specialist:{type:"string",enum:["brand"]}, positioning:stringSchema,audiencePromise:stringSchema,differentiation:stringSchema,identityDirection:{type:"string",enum:["FACELESS","PERSONAL_BRAND","HYBRID"]},identityRationale:stringSchema,trustStrategy:stringSchema,memorabilityStrategy:stringSchema,extensibility:stringSchema,visualDirection:stringSchema,channelArchitectureRelationship:stringSchema,
  }, [...commonRequired,"positioning","audiencePromise","differentiation","identityDirection","identityRationale","trustStrategy","memorabilityStrategy","extensibility","visualDirection","channelArchitectureRelationship"]),
  growth: objectSchema({ contract:{type:"string",enum:["STRATEGY_COUNCIL_GROWTH_V2"]}, ...commonProperties,
    specialist:{type:"string",enum:["growth"]}, platformPriority:{type:"array",minItems:3,maxItems:3,items:{type:"object",additionalProperties:false,properties:{platform:{type:"string",enum:["Instagram Reels","YouTube Shorts","TikTok"]},priority:{type:"number"},rationale:stringSchema},required:["platform","priority","rationale"]}},launchSequence:stringArray,cadenceDirection:stringSchema,experimentationFramework:stringArray,crossPlatformReuse:stringSchema,acquisitionMechanics:stringArray,retentionMechanics:stringArray,tractionSignals:stringArray,scalingGates:stringArray,channelArchitectureImplications:stringSchema,expansionTriggers:stringArray,deferredActions:stringArray,
  }, [...commonRequired,"platformPriority","launchSequence","cadenceDirection","experimentationFramework","crossPlatformReuse","acquisitionMechanics","retentionMechanics","tractionSignals","scalingGates","channelArchitectureImplications","expansionTriggers","deferredActions"]),
  finance: objectSchema({ contract:{type:"string",enum:["STRATEGY_COUNCIL_FINANCE_V2"]}, ...commonProperties,
    specialist:{type:"string",enum:["finance"]},lowestPracticalLaunchBudget:stringSchema,fixedCostCategories:stringArray,variableCostCategories:stringArray,toolProductionCostExposure:stringArray,lowCostStartingOptions:stringArray,laterPaidUpgrades:stringArray,monetizationRoutes:stringArray,monetizationDependencies:stringArray,reinvestmentStrategy:stringSchema,breakEvenConsiderations:stringSchema,financialScalingGates:stringArray,
    milestones:{type:"array",minItems:3,maxItems:3,items:{type:"object",additionalProperties:false,properties:{monthlyUsd:{type:"number",enum:[100,1000,10000]},economics:stringSchema,requirements:stringSchema,risks:stringSchema},required:["monthlyUsd","economics","requirements","risks"]}},
  }, [...commonRequired,"lowestPracticalLaunchBudget","fixedCostCategories","variableCostCategories","toolProductionCostExposure","lowCostStartingOptions","laterPaidUpgrades","monetizationRoutes","monetizationDependencies","reinvestmentStrategy","breakEvenConsiderations","financialScalingGates","milestones"]),
};

const commonExample = (specialist:StrategyCouncilV2Specialist,contract:string) => ({contract,specialist,status:"COMPLETED",objective:"example strategic objective",recommendations:["example strategic recommendation"],risks:["example strategic risk"],tradeoffs:["example strategic tradeoff"],assumptionsAndUnknowns:[{statement:"example unknown",classification:"UNKNOWN"}],sourceArtifactReferences:[{artifactId:"example-upstream-artifact",kind:"example_upstream_kind"}]});
export const STRATEGY_COUNCIL_V2_EXAMPLES:Record<StrategyCouncilV2Specialist,Json> = {
 writer:{...commonExample("writer","STRATEGY_COUNCIL_WRITER_V2"),storytellingArchitecture:"example architecture",hookMechanics:["example hook"],repeatableSeries:[{series:"example series",format:"example format",strategicPurpose:"example purpose"}],shortFormSuitability:"example suitability",emotionalDepth:"example emotional treatment",educationalDepth:"example educational treatment",globalComprehension:"example comprehension approach",languageStrategy:"example language approach",productionRepeatability:"example repeatability approach",contentFatigueRisk:"example fatigue risk",representativeDirections:["example strategic direction"]},
 seo:{...commonExample("seo","STRATEGY_COUNCIL_SEO_V2"),discoverabilityArchitecture:"example architecture",topicFamilies:["example topic family"],topicFraming:["example framing"],discoveryIntent:"example intent",platformImplications:["Instagram Reels","YouTube Shorts","TikTok"].map(platform=>({platform,implication:"example platform implication"})),evergreenTrendBalance:"example balance",titleCaptionPrinciples:["example principle"],saturationRisks:["example saturation risk"]},
 brand:{...commonExample("brand","STRATEGY_COUNCIL_BRAND_V2"),positioning:"example positioning",audiencePromise:"example promise",differentiation:"example differentiation",identityDirection:"HYBRID",identityRationale:"example rationale",trustStrategy:"example trust approach",memorabilityStrategy:"example memorability approach",extensibility:"example extensibility",visualDirection:"example visual direction",channelArchitectureRelationship:"example relationship"},
 growth:{...commonExample("growth","STRATEGY_COUNCIL_GROWTH_V2"),platformPriority:["Instagram Reels","YouTube Shorts","TikTok"].map((platform,index)=>({platform,priority:index+1,rationale:"example priority rationale"})),launchSequence:["example launch step"],cadenceDirection:"example cadence",experimentationFramework:["example experiment"],crossPlatformReuse:"example reuse",acquisitionMechanics:["example acquisition mechanic"],retentionMechanics:["example retention mechanic"],tractionSignals:["example signal"],scalingGates:["example gate"],channelArchitectureImplications:"example implication",expansionTriggers:["example trigger"],deferredActions:["example deferred action"]},
 finance:{...commonExample("finance","STRATEGY_COUNCIL_FINANCE_V2"),lowestPracticalLaunchBudget:"UNKNOWN pending verified inputs",fixedCostCategories:["example fixed category"],variableCostCategories:["example variable category"],toolProductionCostExposure:["UNKNOWN actual provider cost"],lowCostStartingOptions:["example low-cost option"],laterPaidUpgrades:["example conditional upgrade"],monetizationRoutes:["example route"],monetizationDependencies:["example dependency"],reinvestmentStrategy:"example reinvestment approach",breakEvenConsiderations:"example break-even consideration",financialScalingGates:["example financial gate"],milestones:[100,1000,10000].map(monthlyUsd=>({monthlyUsd,economics:"example scenario economics",requirements:"example requirement",risks:"example risk"}))},
};

const missions:Record<StrategyCouncilV2Specialist,string> = {
 writer:"storytelling architecture, hooks, structured repeatable series, short-form suitability, emotional and educational depth, global comprehension, language implications, repeatability, fatigue risk, and strategic content directions; never produce a final post or script",
 seo:"discoverability architecture, topic families/framing, intent, three platform implications, evergreen/trend balance, framing principles, and saturation risk; never fabricate metrics",
 brand:"positioning, audience promise, differentiation, identity direction, trust, memorability, extensibility, visual direction, and channel architecture; never finalize names or handles",
 growth:"platform priorities, launch sequence, cadence, experiments, reuse, acquisition, retention, traction, scaling, expansion, and deferrals; never guarantee growth. Express growth outcomes as hypotheses, scenarios, experiments, estimates, or conditional expectations. Never claim or imply guaranteed outcomes, guaranteed virality, risk-free growth, or that a strategy will definitely earn, reach, or grow. Use calibrated language such as may, could, expected, estimated, target, hypothesis, test, scenario, or conditional outcome",
 finance:"budget and cost categories, low-cost options, upgrades, monetization, reinvestment, break-even, scaling gates, and three revenue scenarios; unsupported actual costs remain UNKNOWN and revenue is never guaranteed",
};
export const STRATEGY_COUNCIL_V2_SYSTEM_PROMPTS = Object.fromEntries(Object.keys(schemas).map(id=>[id,`You are the ${id} strategy specialist for Strategy Council V2. Analyze only supplied canonical evidence and cover ${missions[id as StrategyCouncilV2Specialist]}. Return exactly one JSON object matching the supplied schema. Do not disclose chain-of-thought. Owner approval remains pending.`])) as Record<StrategyCouncilV2Specialist,string>;
export const strategyCouncilV2Schema = (id:StrategyCouncilV2Specialist):JsonSchema => schemas[id];

type Issue = {path:string;code:string;expected?:string;actual?:unknown;actualCount?:number};
const rec=(value:unknown):value is Record<string,unknown>=>value!==null&&typeof value==="object"&&!Array.isArray(value);
function inspectShape(value:unknown,schema:JsonSchema,path:string,issues:Issue[]):void {
  const type=schema.type;
  if(type==="object"){
    if(!rec(value)){issues.push({path,code:"wrong_type",expected:"object",actual:value});return;}
    const properties=rec(schema.properties)?schema.properties:{};
    for(const key of Array.isArray(schema.required)?schema.required:[])if(typeof key==="string"&&value[key]===undefined)issues.push({path:path==="$"?key:`${path}.${key}`,code:"missing_required"});
    if(schema.additionalProperties===false)for(const key of Object.keys(value))if(properties[key]===undefined)issues.push({path:path==="$"?key:`${path}.${key}`,code:"unrecognized_field"});
    for(const [key,child] of Object.entries(properties))if(value[key]!==undefined&&rec(child))inspectShape(value[key],child as JsonSchema,path==="$"?key:`${path}.${key}`,issues);
  }else if(type==="array"){
    if(!Array.isArray(value)){issues.push({path,code:"wrong_type",expected:"array",actual:value});return;}
    const min=typeof schema.minItems==="number"?schema.minItems:undefined,max=typeof schema.maxItems==="number"?schema.maxItems:undefined;
    if((min!==undefined&&value.length<min)||(max!==undefined&&value.length>max))issues.push({path,code:min===max?"exact_count":"bounded_count",expected:min===max?String(min):`${min??0}..${max??"unbounded"}`,actual:value,actualCount:value.length});
    if(rec(schema.items))value.forEach((item,index)=>inspectShape(item,schema.items as JsonSchema,`${path}[${index}]`,issues));
  }else if(type==="string"&&typeof value!=="string")issues.push({path,code:"wrong_type",expected:"string",actual:value});
  else if(type==="number"&&(typeof value!=="number"||!Number.isFinite(value)))issues.push({path,code:"wrong_type",expected:"number",actual:value});
  if(Array.isArray(schema.enum)&&!schema.enum.includes(value as never))issues.push({path,code:"invalid_enum",expected:schema.enum.join("|"),actual:value});
}

export function validateStrategyCouncilSpecialistV2(id:StrategyCouncilV2Specialist,value:Json):StrategyCouncilSpecialistV2Output {
  const issues:Issue[]=[];inspectShape(value,schemas[id],"$",issues);
  if(issues.length)throw new BoundedStructuralValidationError(`Invalid ${id} V2 strategy response`,boundedStructuralDiagnostics(id,String((schemas[id].properties as Record<string,any>).contract.enum[0]),value,issues,["assumptionsAndUnknowns","sourceArtifactReferences"]));
  const root=value as unknown as Record<string,unknown>,text=JSON.stringify(value);
  if(/guaranteed|guarantee[sd]?|risk[- ]free|will (?:earn|reach|grow)/i.test(text))throw new Error("SEMANTIC_VALIDATION_FAILED: prohibited guarantee");
  if(id==="brand"&&/(?:final name|channel name|handle is|call it)\s*[:=]?/i.test(text))throw new Error("SEMANTIC_VALIDATION_FAILED: naming boundary");
  if(id==="seo"&&/(?:search volume|monthly searches)\s*[:=]\s*\d/i.test(text))throw new Error("SEMANTIC_VALIDATION_FAILED: fabricated discovery metric");
  if(id==="finance"&&(/\$\d+(?:\.\d+)?\s*(?:per|\/)(?:image|video|request)/i.test(text)||JSON.stringify((root.milestones as any[]).map(x=>x.monthlyUsd).sort((a,b)=>a-b))!=="[100,1000,10000]"))throw new Error("SEMANTIC_VALIDATION_FAILED: finance cost or milestone policy");
  if((id==="growth"&&new Set((root.platformPriority as any[]).map(x=>x.platform)).size!==3)||(id==="seo"&&new Set((root.platformImplications as any[]).map(x=>x.platform)).size!==3))throw new Error("SEMANTIC_VALIDATION_FAILED: exact platform set required");
  if(!(root.recommendations as unknown[]).length||!(root.sourceArtifactReferences as unknown[]).length)throw new Error("SEMANTIC_VALIDATION_FAILED: substantive recommendations and lineage required");
  return value as unknown as StrategyCouncilSpecialistV2Output;
}

function outputRules(id:StrategyCouncilV2Specialist):string {
  return `OUTPUT SCHEMA (machine-readable): ${JSON.stringify(schemas[id])}\nEXACT VALID SHAPE TEMPLATE (neutral placeholders only): ${JSON.stringify(STRATEGY_COUNCIL_V2_EXAMPLES[id])}\nOUTPUT RULES: Return exactly one JSON object. No Markdown fences. No commentary before or after JSON. No prose outside JSON. Use exact field names. Include every required field. Do not add unrecognized top-level or nested fields. Never replace strings, numbers, or enum primitives with explanatory objects. Never replace arrays with objects. Never add wrapper objects around primitive fields. Obey enum values and array cardinalities exactly.`;
}
export function strategyCouncilV2OutputInstructions(id:StrategyCouncilV2Specialist):string{return outputRules(id);}
export function createStrategyCouncilV2SpecialistAgent(id:StrategyCouncilV2Specialist,execute:(context:ExecutionContext,request:ExecutionRequest,signal:CancellationToken)=>Promise<ExecutionResponse>){return {async executeAgent(input:{context:ExecutionContext;input:Json},signal:CancellationToken){const raw=rec(input.input)?input.input:{},evidence=Array.isArray(raw.validatedArtifacts)?raw.validatedArtifacts:[];const projection=evidence.slice(0,7).map(item=>{const r=rec(item)?item:{};return {artifactId:r.artifactId,kind:r.kind,producerAgent:r.producerAgent,payload:JSON.stringify(r.payload??{}).slice(0,2400)};});const overrides=rec(raw.controlAgentOverrides)?raw.controlAgentOverrides:{};const scoped=rec(overrides[id])?overrides[id]:{};const canonical=rec(scoped.canonicalRouting)?scoped.canonicalRouting:{};if(typeof scoped.model!=="string"||!scoped.model.trim()||typeof canonical.routingVersionId!=="string"||typeof canonical.priceSnapshotId!=="string")throw new Error(`CANONICAL_SPECIALIST_ROUTE_REQUIRED:${id}`);const model=scoped.model.trim();const nativeCanary=false;const roleSection=id==="writer"&&(model.startsWith("claude-")||nativeCanary)?"":`A. SYSTEM ROLE\n${STRATEGY_COUNCIL_V2_SYSTEM_PROMPTS[id]}\n`;const prompt=`${roleSection}B. BOUNDED BUSINESS INPUT\nObjective: ${String(raw.objective??"Produce specialist strategy")}\nCanonical evidence projection: ${JSON.stringify(projection)}\nC. OUTPUT CONTRACT\n${outputRules(id)}`;const request:ExecutionRequest={model,system:STRATEGY_COUNCIL_V2_SYSTEM_PROMPTS[id],messages:[{role:"system",content:STRATEGY_COUNCIL_V2_SYSTEM_PROMPTS[id]},{role:"user",content:prompt}],temperature:0.2,maxOutputTokens:8192,responseSchema:schemas[id]};const response=await execute(input.context,request,signal);return {output:validateStrategyCouncilSpecialistV2(id,response.output) as unknown as Json,response};}};}
