import { strictEqual, deepStrictEqual, ok } from "node:assert";
import { describe, it } from "node:test";
import { QualityWorkflow } from "../dist/index.js";

const context = { workflowId: "workflow-q", correlationId: "correlation-q", brandId: null, outputs: {}, data: { objective: "Validate release" } };
const stages = { upstreamStages: [{ step: { id: "planner", kind: "agent", agent: "planner", emits: "plan" }, artifactKind: "execution_plan" }, { step: { id: "research", kind: "agent", agent: "research", emits: "research" }, artifactKind: "research_report" }], reviewLoop: { codingStep: { id: "coding", kind: "agent", agent: "coding", emits: "coding" }, reviewerStep: { id: "reviewer", kind: "agent", agent: "reviewer", emits: "review" }, maxReviewIterations: 2 }, qaStep: { id: "qa", kind: "agent", agent: "qa", emits: "qa" }, documentationStep: { id: "documentation", kind: "agent", agent: "documentation", emits: "documentation" }, maxQAIterations: 2 };
function artifact(kind, producerAgent, artifactId, payload, parentArtifact) { return { artifactId, kind, producerAgent, workflowId: context.workflowId, correlationId: context.correlationId, status: "completed", payload, contentType: "application/json", schemaVersion: "1.0", createdAt: "2026-08-10T00:00:00.000Z", ...(parentArtifact ? { parentArtifact: { artifactId: parentArtifact.artifactId, kind: parentArtifact.kind } } : {}) }; }
function fakeExecutor(qaStatuses = ["passed"], options = {}) {
  const calls = [];
  let sequence = 0;
  const executor = { executeAgentStep: async (step, currentContext) => {
    calls.push({ agent: step.agent, context: currentContext });
    if (options.failAgent === step.agent) return { status: "failed", output: {}, error: { message: `${step.agent} failed`, retryable: false } };
    const previous = currentContext.data.previousArtifact;
    const parent = previous ? { artifactId: previous.artifactId, kind: previous.kind } : undefined;
    if (step.agent === "planner") return { status: "completed", output: {}, artifact: artifact("execution_plan", "planner", "plan-1", { planId: "plan-1", objective: "Validate release", tasks: [] }) };
    if (step.agent === "research") return { status: "completed", output: {}, artifact: artifact("research_report", "research", "research-1", { reportId: "research-1", taskDescription: "plan", summary: "researched", sources: [] }, parent) };
    if (step.agent === "coding") { sequence += 1; return { status: "completed", output: {}, artifact: artifact("coding_report", "coding", `coding-${sequence}`, { resultId: `coding-${sequence}`, taskDescription: "code", status: "completed", summary: "analysis", actions: [] }, parent) }; }
    if (step.agent === "reviewer") return { status: "completed", output: {}, artifact: artifact("review_report", "reviewer", `review-${sequence}`, { reportId: `review-${sequence}`, taskDescription: "code", status: "approved", summary: "pass", findings: [{ id: "review-finding", description: "keep in feedback" }] }, parent) };
    if (step.agent === "qa") { const status = qaStatuses[calls.filter((call) => call.agent === "qa").length - 1] ?? "passed"; return { status: "completed", output: {}, artifact: artifact("qa_report", "qa", `qa-${calls.filter((call) => call.agent === "qa").length}`, { reportId: "qa", objective: "release", status, summary: "qa", testResults: status === "passed" && options.noEvidence !== true ? [{ testName: "smoke", status: "passed", executed: true, source: "runtime", evidence: "runner pass" }] : [], executionEvidencePresent: status === "passed" && options.noEvidence !== true }, parent) }; }
    if (step.agent === "documentation") { return { status: "completed", output: {}, artifact: artifact("documentation_report", "documentation", "doc-1", { resultId: "doc-1", objective: "release", status: "generated", summary: "validated", sections: [], generatedOnly: true, persistence: "not_written" }, parent) }; }
    return { status: "failed", output: {}, error: { message: `Agent not found: ${step.agent}`, retryable: false } };
  } };
  return { executor, calls };
}

describe("QualityWorkflow", () => {
  it("gates QA behind Reviewer PASS and Documentation behind QA PASS", async () => { const fake = fakeExecutor(); const result = await new QualityWorkflow(fake.executor).run(stages, context); strictEqual(result.status, "completed"); strictEqual(result.output.kind, "documentation_report"); deepStrictEqual(fake.calls.map((call) => call.agent), ["planner", "research", "coding", "reviewer", "qa", "documentation"]); strictEqual(fake.calls[4].context.workflowId, context.workflowId); strictEqual(fake.calls[4].context.correlationId, context.correlationId); });
  it("routes QA FAIL through Coding → Reviewer → QA", async () => { const fake = fakeExecutor(["failed", "passed"]); const result = await new QualityWorkflow(fake.executor).run(stages, context); strictEqual(result.status, "completed"); deepStrictEqual(fake.calls.map((call) => call.agent), ["planner", "research", "coding", "reviewer", "qa", "coding", "reviewer", "qa", "documentation"]); strictEqual(fake.calls[5].context.data.reviewFindings[0].id, "review-finding"); strictEqual(fake.calls[5].context.data.qaFeedback.status, "failed"); });
  it("keeps QA blocked and not-executed states terminal", async () => { const blocked = await new QualityWorkflow(fakeExecutor(["blocked"]).executor).run(stages, context); strictEqual(blocked.status, "qa_blocked"); const notExecuted = await new QualityWorkflow(fakeExecutor(["not_executed"]).executor).run(stages, context); strictEqual(notExecuted.status, "qa_not_executed"); });
  it("rejects QA PASS without explicit runtime evidence", async () => { const result = await new QualityWorkflow(fakeExecutor(["passed"], { noEvidence: true }).executor).run(stages, context); strictEqual(result.status, "qa_invalid"); });
  it("rejects malformed QA results and prevents Documentation", async () => { const fake = fakeExecutor(); const malformed = { executeAgentStep: async (step, currentContext) => step.agent === "qa" ? { status: "completed", output: {}, artifact: artifact("qa_report", "qa", "qa-1", { reportId: "qa", objective: "release", status: "unknown", testResults: [], executionEvidencePresent: false }, { artifactId: "review-1", kind: "review_report" }) } : fake.executor.executeAgentStep(step, currentContext) }; const result = await new QualityWorkflow(malformed).run(stages, context); strictEqual(result.status, "qa_invalid"); ok(!fake.calls.some((call) => call.agent === "documentation")); });
  it("enforces QA iteration limit", async () => { const fake = fakeExecutor(["failed", "failed"]); const result = await new QualityWorkflow(fake.executor).run({ ...stages, maxQAIterations: 2 }, context); strictEqual(result.status, "qa_limit_reached"); strictEqual(result.qaIterations, 2); });
  it("stops on QA execution failure or unknown agent", async () => { const failed = await new QualityWorkflow(fakeExecutor([], { failAgent: "qa" }).executor).run(stages, context); strictEqual(failed.status, "failed"); const unknown = await new QualityWorkflow({ executeAgentStep: async (step) => ({ status: "failed", output: {}, error: { message: `Agent not found: ${step.agent}`, retryable: false } }) }).run({ ...stages, upstreamStages: [{ step: { ...stages.upstreamStages[0].step, agent: "unknown" }, artifactKind: "execution_plan" }] }, context); strictEqual(unknown.status, "failed"); });
  it("preserves complete lineage through QA and Documentation", async () => { const result = await new QualityWorkflow(fakeExecutor().executor).run(stages, context); strictEqual(result.lineage.at(-1).kind, "documentation_report"); strictEqual(result.lineage.at(-1).parentArtifact.artifactId, "qa-1"); deepStrictEqual(result.lineage.map((item) => item.workflowId), result.lineage.map(() => context.workflowId)); deepStrictEqual(result.lineage.map((item) => item.correlationId), result.lineage.map(() => context.correlationId)); });
  it("prevents Documentation after invalid upstream artifacts", async () => { const fake = fakeExecutor(); const invalid = { executeAgentStep: async (step, currentContext) => step.agent === "reviewer" ? { status: "completed", output: {}, artifact: artifact("review_report", "reviewer", "review-1", { reportId: "r", taskDescription: "code", status: "blocked", summary: "blocked", findings: [] }, { artifactId: "coding-1", kind: "coding_report" }) } : fake.executor.executeAgentStep(step, currentContext) }; const result = await new QualityWorkflow(invalid).run(stages, context); strictEqual(result.status, "failed"); ok(!fake.calls.some((call) => call.agent === "documentation")); });
});
