import { strictEqual, deepStrictEqual, ok } from "node:assert";
import { describe, it } from "node:test";
import { ReviewerFeedbackLoop } from "../dist/index.js";

const context = { workflowId: "workflow-1", correlationId: "correlation-1", brandId: null, outputs: {}, data: { objective: "Improve pipeline" } };
const config = { codingStep: { id: "coding", kind: "agent", agent: "coding", emits: "coding" }, reviewerStep: { id: "reviewer", kind: "agent", agent: "reviewer", emits: "review" }, maxReviewIterations: 3 };
function artifact(kind, agent, id, payload, parentArtifact) { return { artifactId: id, kind, producerAgent: agent, workflowId: context.workflowId, correlationId: context.correlationId, status: "completed", payload, contentType: "application/json", schemaVersion: "1.0", createdAt: "2026-08-10T00:00:00.000Z", ...(parentArtifact ? { parentArtifact: { artifactId: parentArtifact.artifactId, kind: parentArtifact.kind } } : {}) }; }
function fakeExecutor(reviewStatuses = ["approved"], options = {}) {
  const calls = [];
  let codingIteration = 0;
  return { calls, executor: { executeAgentStep: async (step, currentContext) => { const reviewerIndex = calls.filter((call) => call.agent === "reviewer").length; calls.push({ agent: step.agent, context: currentContext }); if (options.failAgent === step.agent) return { status: "failed", output: {}, error: { message: `${step.agent} failed`, retryable: false } }; if (step.agent === "coding") { codingIteration += 1; const previous = currentContext.data.previousArtifact; return { status: "completed", output: {}, artifact: artifact("coding_report", "coding", `coding-${codingIteration}`, { resultId: `coding-${codingIteration}`, taskDescription: "code", status: "completed", summary: "Proposed analysis", actions: [] }, previous ? { artifactId: previous.artifactId, kind: previous.kind } : undefined) }; } const previous = currentContext.data.previousArtifact; const status = reviewStatuses[reviewerIndex] ?? "approved"; return { status: "completed", output: {}, artifact: artifact("review_report", "reviewer", `review-${reviewerIndex + 1}`, { reportId: "review", taskDescription: "code", status, summary: "review", findings: status === "changes_requested" ? [{ id: "finding-1", description: "Fix issue" }] : [] }, previous ? { artifactId: previous.artifactId, kind: previous.kind } : undefined) }; } } }; }

describe("ReviewerFeedbackLoop", () => {
  it("continues on PASS", async () => { const fake = fakeExecutor(["approved"]); const result = await new ReviewerFeedbackLoop(fake.executor).run(config, context); strictEqual(result.status, "completed"); strictEqual(result.iterations, 1); deepStrictEqual(fake.calls.map((call) => call.agent), ["coding", "reviewer"]); });
  it("routes FAIL feedback to Coding and then PASS", async () => { const fake = fakeExecutor(["changes_requested", "approved"]); const result = await new ReviewerFeedbackLoop(fake.executor).run(config, context); strictEqual(result.status, "completed"); strictEqual(result.iterations, 2); strictEqual(fake.calls[2].agent, "coding"); strictEqual(fake.calls[2].context.data.reviewFeedback.reviewStatus, "changes_requested"); strictEqual(fake.calls[2].context.data.reviewFeedback.findings[0].id, "finding-1"); });
  it("handles multiple FAIL results and preserves lineage", async () => { const fake = fakeExecutor(["changes_requested", "changes_requested", "approved"]); const result = await new ReviewerFeedbackLoop(fake.executor).run(config, context); strictEqual(result.status, "completed"); deepStrictEqual(result.lineage.map((item) => item.artifactId), ["coding-1", "review-1", "coding-2", "review-2", "coding-3", "review-3"]); strictEqual(result.lineage[2].parentArtifact.artifactId, "review-1"); strictEqual(result.lineage[4].parentArtifact.artifactId, "review-2"); });
  it("terminates at the configured iteration limit", async () => { const fake = fakeExecutor(["changes_requested", "changes_requested", "changes_requested"]); const result = await new ReviewerFeedbackLoop(fake.executor).run({ ...config, maxReviewIterations: 2 }, context); strictEqual(result.status, "limit_reached"); strictEqual(result.iterations, 2); strictEqual(fake.calls.length, 4); });
  it("stops on malformed Reviewer reports", async () => { const fake = fakeExecutor(); const malformed = { executeAgentStep: async (step) => step.agent === "coding" ? { status: "completed", output: {}, artifact: artifact("coding_report", "coding", "coding-1", { resultId: "c", taskDescription: "code", status: "completed", summary: "", actions: [] }) } : { status: "completed", output: {}, artifact: artifact("review_report", "reviewer", "review-1", { reportId: "r", taskDescription: "code", status: "bad", findings: [] }, { artifactId: "coding-1", kind: "coding_report" }) } }; const result = await new ReviewerFeedbackLoop(malformed).run(config, context); strictEqual(result.status, "failed"); ok(result.error.message.includes("Invalid Reviewer status")); });
  it("stops on Coding failure and does not call Reviewer", async () => { const fake = fakeExecutor([], { failAgent: "coding" }); const result = await new ReviewerFeedbackLoop(fake.executor).run(config, context); strictEqual(result.status, "failed"); strictEqual(fake.calls.length, 1); });
  it("fails unknown agent IDs at the execution boundary", async () => { const fake = fakeExecutor(); const unknown = { ...config, codingStep: { ...config.codingStep, agent: "unknown" } }; const result = await new ReviewerFeedbackLoop({ executeAgentStep: async (step) => ({ status: "failed", output: {}, error: { message: `Agent not found: ${step.agent}`, retryable: false } }) }).run(unknown, context); strictEqual(result.status, "failed"); ok(result.error.message.includes("Agent not found")); });
  it("does not treat Reviewer recommendations as Coding execution evidence", async () => { const fake = fakeExecutor(["changes_requested", "approved"]); const result = await new ReviewerFeedbackLoop(fake.executor).run(config, context); strictEqual(result.status, "completed"); strictEqual(result.lineage[2].payload.status, "completed"); strictEqual(result.lineage[2].payload.actions.length, 0); });
});
