import test, { before, after } from "node:test";
import assert from "node:assert/strict";
import pg from "pg";
import { randomUUID } from "node:crypto";
import { createPool, migrate, applyWanSupervisedExecutionMigration, WanSupervisedExecutionStore } from "../dist/index.js";
import { TEST_DATABASE_URL, assertTestDatabaseIsolation } from "./helpers.js";

assertTestDatabaseIsolation();
const pool=createPool({connectionString:TEST_DATABASE_URL}),nonce=randomUUID().replaceAll("-","").slice(0,12),project=`wan-p-${nonce}`,workflow=`wan-wf-${nonce}`,content=`wan-content-${nonce}`,build=`wan-build-${nonce}`;
const visual=(scene)=>`wan-visual-${nonce}-${scene}`,auth=(scene)=>`wan-approval-${nonce}-${scene}`,sha=(scene)=>String(scene).repeat(64).slice(0,64);
let store;
const authorize=(scene,idem=`idem-${nonce}-${scene}`)=>store.authorize({projectId:project,contentId:content,workflowId:workflow,sceneId:scene,sceneVisualArtifactId:visual(scene),sceneVisualSha256:sha(scene),provider:"self-hosted-video",model:"wan2.2",endpointId:"ry49lc45y50ldy",modelConfig:{prompt:`motion ${scene}`},ownerActor:"owner-test",ownerRationale:"bounded single scene",idempotencyIdentity:idem,expectedWorkerBuild:build,operationMode:"TEMPORARY_GOVERNED_LEGACY_ENDPOINT"});

before(async()=>{
  await migrate(pool);await applyWanSupervisedExecutionMigration(pool);await applyWanSupervisedExecutionMigration(pool);store=new WanSupervisedExecutionStore(pool);
  const now=new Date().toISOString();
  await pool.query(`INSERT INTO control_projects(project_id,display_name,status,created_by,created_at,updated_at) VALUES($1,'Wan test','ACTIVE','test',$2,$2)`,[project,now]);
  await pool.query(`INSERT INTO automation_call_budgets(project_id,call_kind,limit_count,used_count,updated_at,max_retries,limit_kind,cost_kind) VALUES($1,'video_generation',5,0,$2,0,'HARD','UNKNOWN')`,[project,now]);
  await pool.query(`INSERT INTO amf_worker_presence(worker_instance_id,build_id,runtime_mode,launcher,node_version,started_at,last_heartbeat_at) VALUES($1,$2,'PERSISTENT_PRODUCTION_WORKER','test','test',$3,$3)`,[`wan-worker-${nonce}`,build,now]);
  for(const scene of ["1","2","3"]){const vp={projectId:project,contentId:content,sceneId:scene,sha256:sha(scene),artifactPathOrReference:`test://${scene}`};await pool.query(`INSERT INTO artifacts(artifact_id,workflow_id,kind,producer_agent,correlation_id,status,payload,content_type,schema_version,created_at) VALUES($1,$2,'scene_visual_artifact','image','test','completed',$3::jsonb,'application/json','1',$4)`,[visual(scene),workflow,JSON.stringify(vp),now]);await pool.query(`INSERT INTO artifacts(artifact_id,workflow_id,kind,producer_agent,correlation_id,status,payload,content_type,schema_version,created_at,parent_artifact_id,parent_artifact_kind) VALUES($1,$2,'wan_authorization','visual','test','completed',$3::jsonb,'application/json','1',$4,$5,'scene_visual_artifact')`,[auth(scene),workflow,JSON.stringify({projectId:project,contentId:content,sceneId:scene,artifactId:visual(scene),semanticVerdict:"PASS",technicalVerdict:"PASS",humanApprovalId:`human-${scene}`}),now,visual(scene)]);}
});
after(async()=>{await pool.query(`DELETE FROM owner_control_audit_events WHERE project_id=$1`,[project]);await pool.query(`DELETE FROM wan_supervised_executions WHERE project_id=$1`,[project]);await pool.query(`DELETE FROM artifacts WHERE workflow_id=$1`,[workflow]);await pool.query(`DELETE FROM amf_worker_presence WHERE worker_instance_id=$1`,[`wan-worker-${nonce}`]);await pool.query(`DELETE FROM automation_call_budgets WHERE project_id=$1`,[project]);await pool.query(`DELETE FROM control_projects WHERE project_id=$1`,[project]);await pool.end()});

test("A/C/D/E: one approved scene creates one durable execution under concurrent duplicates",async()=>{const results=await Promise.all([authorize("1","same-idem"),authorize("1","same-idem")]);assert.equal(results.filter(x=>x.created).length,1);assert.equal(results[0].execution.wanExecutionId,results[1].execution.wanExecutionId);assert.equal((await store.list(project)).length,1);assert.equal(results[0].execution.providerPostCount,0)});
test("M: a different duplicate identity cannot bypass an unresolved scene",async()=>{const r=await authorize("1","different-idem");assert.equal(r.outcome,"EXISTING_EXECUTION_ACTIVE");assert.equal((await store.list(project)).length,1)});
test("E/Q: durable claim persists one POST intent and consumes budget exactly once",async()=>{const [a,b]=await Promise.all([store.claimNext("worker-a"),store.claimNext("worker-b")]);assert.equal([a,b].filter(Boolean).length,1);const e=(a||b);assert.equal(e.state,"SUBMISSION_STARTED");assert.equal(e.providerPostCount,1);assert.equal(e.budgetState,"CONSUMED");assert.equal(Number((await pool.query(`SELECT used_count FROM automation_call_budgets WHERE project_id=$1 AND call_kind='video_generation'`,[project])).rows[0].used_count),1)});
test("F/I/N: acknowledgement progresses once and completion permits only a new Owner authorization",async()=>{const e=(await store.list(project))[0];await store.acknowledge(e.wanExecutionId,"job-1");await store.markGenerating(e.wanExecutionId);const done=await store.complete(e.wanExecutionId,{sha256:"f".repeat(64)});assert.equal(done.state,"COMPLETED");const next=await authorize("1","future-owner-authorization");assert.equal(next.created,true);assert.notEqual(next.execution.authorizationId,e.authorizationId)});
test("H/J/K/L/R: ambiguity is actionable; job attach and import policy add no POST/budget",async()=>{const pending=(await store.list(project)).find(x=>x.state==="AUTHORIZED");const claimed=await store.claimNext("worker-a");assert.equal(claimed.wanExecutionId,pending.wanExecutionId);const manual=await store.requireManualReconciliation(claimed.wanExecutionId,"SUBMISSION_ACK_AMBIGUOUS");assert.equal(manual.state,"MANUAL_RECONCILIATION_REQUIRED");const before=Number((await pool.query(`SELECT used_count FROM automation_call_budgets WHERE project_id=$1 AND call_kind='video_generation'`,[project])).rows[0].used_count);const attached=await store.attachProviderJobId({projectId:project,executionId:manual.wanExecutionId,providerJobId:"owner-job-2",actor:"owner-test",rationale:"manual console evidence"});assert.equal(attached.providerPostCount,1);assert.equal(attached.reconciliationState,"OWNER_JOB_ID_ATTACHED");assert.equal(Number((await pool.query(`SELECT used_count FROM automation_call_budgets WHERE project_id=$1 AND call_kind='video_generation'`,[project])).rows[0].used_count),before);const items=await store.decisionItems(project);assert.ok(items.some(x=>x.targetId===manual.wanExecutionId));assert.deepEqual(items.find(x=>x.targetId===manual.wanExecutionId).business.allowedActions,["ATTACH_PROVIDER_JOB_ID","IMPORT_OWNER_DOWNLOADED_OUTPUT"])});
test("P: project isolation and visual identity fail closed",async()=>{await assert.rejects(store.attachProviderJobId({projectId:"other",executionId:(await store.list(project))[0].wanExecutionId,providerJobId:"x",actor:"owner",rationale:"deny"}),/CROSS_PROJECT|RECONCILIATION_NOT_REQUIRED/);await assert.rejects(store.authorize({projectId:project,contentId:content,workflowId:workflow,sceneId:"3",sceneVisualArtifactId:visual("3"),sceneVisualSha256:"a".repeat(64),provider:"self-hosted-video",model:"wan2.2",endpointId:"ry49lc45y50ldy",modelConfig:{},ownerActor:"owner",ownerRationale:"bad hash",idempotencyIdentity:"bad-hash-idem",expectedWorkerBuild:build,operationMode:"TEMPORARY_GOVERNED_LEGACY_ENDPOINT"}),/SHA256_MISMATCH/)});
