import { strictEqual, ok, rejects } from "node:assert";
import { describe, it } from "node:test";
import { createQAAgent } from "../dist/index.js";

const input = { requestId: "00000000-0000-4000-8000-000000000001", objective: "Validate workflow quality", request: { scope: "workflow engine", requirements: ["retries work"], expectedTests: ["workflow smoke"] } };
const signal = { throwIfCancelled() {} };
const response = (output) => ({ output, raw: "{}", usage: { inputTokens: 1, outputTokens: 1, costUsd: 0 }, model: "test", provider: "test", latencyMs: 1 });
const validOutput = () => ({ reportId: "00000000-0000-4000-8000-000000000002", requestId: input.requestId, objective: input.objective, status: "reviewed", summary: "Reviewed supplied evidence", testResults: [{ testName: "workflow smoke", status: "passed", executed: false, source: "provided-result", evidence: "CI result supplied by requester" }], findings: [{ id: "f-1", severity: "medium", category: "coverage", description: "Coverage evidence is limited", evidence: "supplied result", recommendation: "Run the full suite" }], risks: [{ id: "r-1", description: "Unverified regression risk", severity: "medium", mitigation: "Execute regression tests" }], recommendations: [{ priority: "high", description: "Run unavailable tests", relatedFindingIds: ["f-1"] }], metadata: { createdAt: "2026-08-10T00:00:00.000Z", agentVersion: "1.0.0", executionEvidencePresent: false } });
function agent(execute = async (_context, _request, _signal) => response(validOutput())) { return createQAAgent({ execute, config: {} }); }

describe("QAAgent", () => {
  it("parses a valid structured QA report", async () => { const result = await agent().execute({ context: {}, input }, signal); strictEqual(result.output.status, "reviewed"); strictEqual(result.output.testResults[0].source, "provided-result"); });
  it("rejects missing required response fields", async () => { await rejects(() => agent(async () => response({})).execute({ context: {}, input }, signal), /missing required fields|invalid report structure/); });
  it("rejects malformed and invalid test results", async () => { const output = validOutput(); output.testResults = [{ testName: "x", status: "unknown", executed: false, source: "none" }]; await rejects(() => agent(async () => response(output)).execute({ context: {}, input }, signal), /invalid report structure|malformed test result/); const malformed = validOutput(); malformed.testResults = [{ testName: "x", status: "passed", executed: true, source: "runtime" }]; await rejects(() => agent(async () => response(malformed)).execute({ context: {}, input }, signal), /execution claim lacks evidence/); });
  it("rejects invalid finding severity and category", async () => { const output = validOutput(); output.findings[0].severity = "urgent"; await rejects(() => agent(async () => response(output)).execute({ context: {}, input }, signal), /malformed finding/); const other = validOutput(); other.findings[0].category = "style"; await rejects(() => agent(async () => response(other)).execute({ context: {}, input }, signal), /malformed finding/); });
  it("rejects incomplete QA requests and malformed supplied evidence", async () => { const incomplete = { ...input, objective: "" }; await rejects(() => agent().execute({ context: {}, input: incomplete }, signal), /Invalid QA input/); const malformed = { ...input, request: { ...input.request, suppliedEvidence: [{ testName: "x", status: "passed", executed: true, source: "provided-result" }] } }; await rejects(() => agent().execute({ context: {}, input: malformed }, signal), /Invalid QA input/); });
  it("distinguishes supplied results from actual execution", async () => { const output = validOutput(); const result = await agent(async () => response(output)).execute({ context: {}, input }, signal); strictEqual(result.output.testResults[0].executed, false); strictEqual(result.output.testResults[0].source, "provided-result"); strictEqual(result.output.metadata.executionEvidencePresent, false); });
  it("accepts actual execution only when matching runtime evidence is supplied", async () => { const actualInput = { ...input, request: { ...input.request, suppliedEvidence: [{ testName: "workflow smoke", status: "passed", executed: true, source: "runtime", evidence: "runner output: pass" }] } }; const output = validOutput(); output.status = "passed"; output.summary = "Runtime evidence confirms the test passed."; output.testResults = [{ testName: "workflow smoke", status: "passed", executed: true, source: "runtime", evidence: "runner output: pass" }]; output.metadata.executionEvidencePresent = true; const result = await agent(async () => response(output)).execute({ context: {}, input: actualInput }, signal); strictEqual(result.output.status, "passed"); strictEqual(result.output.metadata.executionEvidencePresent, true); });
  it("rejects contradictory execution metadata", async () => { const output = validOutput(); output.metadata.executionEvidencePresent = true; await rejects(() => agent(async () => response(output)).execute({ context: {}, input }, signal), /contradictory execution evidence/); });
  it("does not accept a successful execution claim without evidence", async () => { const output = validOutput(); output.status = "passed"; output.summary = "Tests passed after execution."; output.testResults = [{ testName: "workflow smoke", status: "passed", executed: false, source: "none" }]; const result = await agent(async () => response(output)).execute({ context: {}, input }, signal); strictEqual(result.output.status, "blocked"); strictEqual(result.output.testResults[0].status, "not_executed"); });
  it("normalizes unsupported passed or failed status without execution evidence", async () => { const output = validOutput(); output.status = "passed"; const result = await agent(async () => response(output)).execute({ context: {}, input }, signal); strictEqual(result.output.status, "reviewed"); });
  it("preserves execution context in the runtime request", async () => { let request; const result = await agent(async (_context, executionRequest) => { request = executionRequest; return response(validOutput()); }).execute({ context: { turnId: "qa-context-1" }, input }, signal); ok(result); ok(request.messages[1].content.includes("qa-context-1")); });
  it("applies factory defaults", () => { const created = agent(); strictEqual(created.name, "QA Agent"); });
});
