import { strictEqual, ok, rejects } from "node:assert";
import { describe, it } from "node:test";
import { createDocumentationAgent } from "../dist/index.js";

const input = { requestId: "00000000-0000-4000-8000-000000000001", objective: "Document the API", request: { type: "api", purpose: "Explain endpoints", audience: "Developers", requiredSections: ["Overview", "Examples"] } };
const response = (output) => ({ output, raw: "{}", usage: { inputTokens: 1, outputTokens: 1, costUsd: 0 }, model: "test", provider: "test", latencyMs: 1 });
const validOutput = () => ({ resultId: "00000000-0000-4000-8000-000000000002", requestId: input.requestId, objective: input.objective, documentationType: "api", status: "generated", summary: "Generated proposal", artifact: { title: "API Guide", documentationType: "api", content: "Overview\nExamples", sections: [{ title: "Overview", content: "Overview", order: 0 }, { title: "Examples", content: "Examples", order: 1 }], generatedOnly: true }, issues: [], recommendations: [], metadata: { createdAt: "2026-08-10T00:00:00.000Z", agentVersion: "1.0.0", persistence: "not_written" } });
const signal = { throwIfCancelled() {} };
function agent(execute = async (_context, _request, _signal) => response(validOutput())) { return createDocumentationAgent({ execute, config: {} }); }

describe("DocumentationAgent", () => {
  it("parses a valid structured documentation result", async () => { const result = await agent().execute({ context: {}, input }, signal); strictEqual(result.output.status, "generated"); strictEqual(result.output.artifact.sections.length, 2); });
  it("rejects missing required response fields", async () => { await rejects(() => agent(async () => response({})).execute({ context: {}, input }, signal), /invalid result structure|missing required fields/); });
  it("rejects malformed sections and invalid order", async () => { const output = validOutput(); output.artifact.sections = [{ title: "", content: "x", order: 1.5 }]; await rejects(() => agent(async () => response(output)).execute({ context: {}, input }, signal), /malformed section/); });
  it("rejects invalid documentation type and status", async () => { const output = validOutput(); output.documentationType = "invalid"; await rejects(() => agent(async () => response(output)).execute({ context: {}, input }, signal), /invalid result structure/); const other = validOutput(); other.status = "published"; await rejects(() => agent(async () => response(other)).execute({ context: {}, input }, signal), /invalid result structure/); });
  it("rejects malformed metadata, issues, and recommendations", async () => { const output = validOutput(); output.metadata.persistence = "saved"; await rejects(() => agent(async () => response(output)).execute({ context: {}, input }, signal), /malformed metadata/); const issue = validOutput(); issue.issues = [{ code: "GAP", description: "missing", severity: "urgent" }]; await rejects(() => agent(async () => response(issue)).execute({ context: {}, input }, signal), /malformed issue/); const recommendation = validOutput(); recommendation.recommendations = [{ priority: "high" }]; await rejects(() => agent(async () => response(recommendation)).execute({ context: {}, input }, signal), /malformed recommendation/); });
  it("rejects incomplete documentation requests", async () => { const incomplete = { ...input, objective: "", request: { ...input.request, purpose: "" } }; await rejects(() => agent().execute({ context: {}, input: incomplete }, signal), /Invalid documentation input/); });
  it("blocks unsupported file, save, and publish claims", async () => { const output = validOutput(); output.summary = "The document was saved and published."; const result = await agent(async () => response(output)).execute({ context: {}, input }, signal); strictEqual(result.output.status, "blocked"); strictEqual(result.output.artifact.generatedOnly, true); strictEqual(result.output.metadata.persistence, "blocked"); });
  it("blocks a file-creation claim without a writing tool", async () => { const output = validOutput(); output.artifact.sections[0].content = "The file was created successfully."; const result = await agent(async () => response(output)).execute({ context: {}, input }, signal); strictEqual(result.output.status, "blocked"); });
  it("preserves execution context in the request", async () => { let request; const result = await agent(async (_context, executionRequest) => { request = executionRequest; return response(validOutput()); }).execute({ context: { turnId: "context-123" }, input }, signal); ok(result); ok(request.messages[1].content.includes("context-123")); });
  it("applies factory defaults", () => { const created = agent(); strictEqual(created.name, "Documentation Agent"); });
});
